---
title: "Lab 00 - Hello IDS!"
author: "Max Pohlman"
date: "`r Sys.Date()`"
output: html_document
---
```{r load-packages, message=FALSE}
library(tidyverse) 
```
```{r setup-tibble}
team_data <- tibble(
  name = c("Andrew", "Helen", "Adam", 
           "Max", "Sarah", "Liv"),
  github_username = c("pukklemaster", "helenmiller", "adamlaycock", 
                      "MaxwellPohlman", "sarahstewart142", "oliviaharris1"),
  colour = c("mediumaquamarine", "thistle1", "forestgreen", 
             "slategray3", "powderblue", "violetred"),
  hobby = c("Knitting", "Crochet", "Guitar", 
            "Climbing", "Swimming", "Net Ball"),
  favourite_number = c(7, 4, 7, 10, 6, 4)
  )
```

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```




Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "github_username", 
          y = "favourite_number",
          title = "GitHub Username and Favourite Number")
```

*Remove this text (including the stars), and add your answer for Exercise 19 here.*

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

*Remove this text (including the stars) and add your answer for Exercise 20 here.*
